### ISSUE TITLE
Gitlab and consolidate_comments

### ISSUE THREAD

**Issue by tleish** [prontolabs/pronto#239]
Does the consolidate_comments config option work for Gitlab?  I have the following in .pronto.yml and it doesn't seem to be consolidating them.

```yaml
all:
  exclude:
    - 'spec/**/*'
gitlab:
  slug: XXX
  api_private_token: XXX
  api_endpoint: XXX
  gitlab_api_httparty_options: "{verify: false}"
  format: "**%{runner} [%{level}]:** %{msg}"
max_warnings: 150
verbose: false
consolidate_comments: true
```

Or perhaps I'm mis-understanding the feature.  The problem is, when pronto runs and finds multiple items to report, it posts multiple comments in Gitlab and ultimately several people get spammed with lots of emails instead of just one comment and one email.  I was hoping this would solve it.
