### ISSUE TITLE
GitLab formatter

### ISSUE THREAD

**Issue by jeroenj** [prontolabs/pronto#25]
Since we are using GitLab at our company it would be nice to have GitLab formatter.
I already started working on it and I've got a working formatter but it's far from completed: https://github.com/jeroenj/pronto/tree/gitlab-formatter.
I'll try to clean it up when I find the time, but I'm already putting it here for anybody who's interested to help out.
There also needs to be some work done in the GitLab API to improve this code.

**Comment by Schwad** [comment]
Does this still work? I'm getting the following error trying gitlab integration:  @mmozuras 

```
/home/gitlab-runner/builds/c1b1565f/0/MY/PATH/vendor/bundle/ruby/2.3.0/gems/gitlab-4.2.0/lib/gitlab/request.rb:37:in `rescue in decode': The response is not a valid JSON (Gitlab::Error::Parsing)
```

If my issue is unrelated or config problem on my end I'll fire up a separate issue.

**Comment by Schwad** [comment]
Okay, so, I fought long and hard enough with getting the Gitlab integration done that I posted here.... But needed to get this live *stat*.Iif anyone else is struggling and just wants their integration fired up and working shove this in your gitlab CI and you won't need the gitlab formatter:

```
rubocop:
  stage: rubocop
  script:
      - var="$(bundle exec pronto run -r rubocop -c origin/master)"
      - echo $var
      - if [[ -z $var ]]; then exit 0; else exit 1; fi
```

Hopefully I get the configuration sorted some other time.
