### ISSUE TITLE
Gitlab CI integration pipeline

### ISSUE THREAD

**Issue by zhisme** [prontolabs/pronto#350]
Hello, I cannot understand at all how to integrate this to Gitlab CI as part pipelines of `.gitlab-ci.yml`
README just says about some tokens, not describing where to get them.
As I understand README is written like I run the following commands on my local. But why I need this, I want automation. 

As I see it should work, like rspec pipeline for example.
```
1. I push feature branch
2. Pipeline jobs start
3. If any issues, post them in following job
4. Applicable to pronto-rubocop, post messages on git diff for code style errors
```

Is it supposed to be used this way, or am I misled?

**Comment by zhisme** [comment]
So I have found solution.
I made a docker script for this.

pronto
```
FROM ruby:2.3.3

RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		cmake \
	&& rm -rf /var/lib/apt/lists/*

ENV RUBOCOP_VERSION XXX
ENV PRONTO_VERSION XXX

RUN echo 'gem: --no-rdoc --no-ri' >> /.gemrc \
	&& gem install rubocop --version $RUBOCOP_VERSION \
  && gem install pronto --version $PRONTO_VERSION \
  && gem install pronto-rubocop

CMD [ "bash" ]
```

Then in my `gitlab-ci.yml`
```yml
PRONTO_GITLAB_API_ENDPOINT: https://gitlab.com/api/v4
PRONTO_GITLAB_API_PRIVATE_TOKEN: nniw-gevMRyiZ64nXGne # this can be created in gitlab 
# Account -> Settings -> Access Tokens (also I would advise to create technical user for this, otherwise comments will be from your name). 

lint:
  stage: test
  image: where-you-put-container.com/devops/containers:pronto-lint
  script:
   - PRONTO_GITLAB_API_ENDPOINT=$PRONTO_GITLAB_API_ENDPOINT PRONTO_GITLAB_API_PRIVATE_TOKEN=$PRONTO_GITLAB_API_PRIVATE_TOKEN pronto run -r rubocop --commit=origin/master --formatters=gitlab --exit-code
```

Then after `git origin push feature-branch` it will run pipeline job for this, and automatically create comments. I think you need to add these to wiki or somewhere.
