### ISSUE TITLE
github validation failed - diff_hunk

### ISSUE THREAD

**Issue by louman** [prontolabs/pronto#411]
Hi there, I'm setting up pronto and using reek as the first runner to get the ball rolling however I'm getting a github API validation error.

.pronto.yml

```
all:
  exclude:
    - 'spec/**/*'
verbose: true
github:
  slug: ***
  access_token: ***

```

command:

```
 pronto run -f github_pr -c origin/develop --staged --runner reek
```

error:

```
Creating pull request comment on 22697
Failed to post: POST https://api.github.com/repos/***/***/pulls/22697/comments: 422 - Validation Failed
Error summary:
  resource: PullRequestReviewComment
  code: invalid
  field: pull_request_review_thread.path
  resource: PullRequestReviewComment
  code: missing_field
  field: pull_request_review_thread.diff_hunk // See: https://docs.github.com/rest
```

Am I missing any configuration? Any help appreciated.
