### ISSUE TITLE
undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by datpmt** [prontolabs/pronto#448]
![image](https://github.com/prontolabs/pronto/assets/76593070/26508c4d-d52e-43a1-a2a3-525a05c7edfc)
This appeared 3 weeks ago, any help would be very helpful to me. Thanks!

my `pronto.yml`
```
name: Rubocop Check
on: [pull_request]

jobs:
  pronto:
    permissions: write-all
    name: 'Rubocop Check'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          git fetch
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - name: Setup pronto
        run: gem install pronto pronto-rubocop
      - name: Run Pronto
        run: pronto run -f github_status github_pr -c origin/${{ github.base_ref }}
        env:
          PRONTO_PULL_REQUEST_ID: ${{ github.event.pull_request.number }}
          PRONTO_GITHUB_ACCESS_TOKEN: "${{ github.token }}"
```

`pronto (~> 0.11.0)`
`pronto-flay (~> 0.11.0)`
`pronto-rubocop (~> 0.11.1)`
`rubocop (= 1.14.0)`
`rails (~> 6.1.5)`
