### ISSUE TITLE
Uninitialized constant RuboCop::Lockfile::Bundler 

### ISSUE THREAD

**Issue by sramsden** [prontolabs/pronto#461]
Just started seeing this yesterday.
I can't work out if this is a rubocop or pronto thing, so apologies if it's rubocop.
It's rubocop _code_ but it's complaint sounds like pronto is not loading the required class?
Has anyone seen this?
I am running pronto as a github action..
```
jobs:
  pronto:
    if: ${{ github.ref != 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - run: git fetch --no-tags --prune --depth=10 origin master:master
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - name: Setup pronto
        run: gem install pronto pronto-rubocop rubocop-rails
      - name: Run Pronto
        run: pronto run --commit $(git merge-base --fork-point master) --runner rubocop --exit-code
```

<img width="1111" alt="image" src="https://github.com/prontolabs/pronto/assets/8897694/aba3fe40-57a1-430c-b576-d67de767baeb">
